name: CodeCov

on:
  pull_request:
    branches: [ "main", "develop"]
  push:
    branches: ["develop"]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'docs/**'
    tags:
      - "v*"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true



jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pytest --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
