name: Pytest

on:
  pull_request:
    branches: [ "main", "develop"]
  push:
    branches: ["develop"]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'docs/**'
    tags:
      - "v*"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: pytest --cov=uptainer tests/
